#!/bin/sh

res=0
# add call to local hook
local_hook="$(dirname $0)/../hooks_local/$(basename $0)"
if [ -f "$local_hook" ]; then
	$local_hook "$@"
	res=$?
fi

case "$1" in
	rebase) exec .git/hooks/post-merge ;;
esac

exit $res
