#!/bin/sh

SOURCE=$(dirname $(readlink -f $0))
res=0
# add call to local hook
local_hook="$(dirname $0)/../hooks_local/$(basename $0)"
if [ -f "$local_hook" ]; then
	$local_hook "$@"
	res=$?
fi

if [ $res -eq 0 ]; then
	# Do not run german practice when amending or fixing commits up
	if ps -ocommand= -p $PPID | grep -Eq "(--fixup|--amend|--squash)"; then exit $res; fi
	if [ ! -z "$GERMAN_PRACTICE" ]; then
		# Practice German every time I commit
		exec < /dev/tty
		german-practice random 5
	fi
fi

exit $res
