#!/bin/bash

volumeicon &

## Set startup volume
pactl set-sink-volume 0 '20%' &

## Disable beeps
xset -b &

## DPMS monitor setting (standby -> suspend -> off) (seconds)
xset dpms 300 600 900 &

## Set LCD brightness
xbacklight -set 90 &

## Set the keyboard layouts, uk and dvorak with compose key
setxkbmap -option grp:switch,grp:shifts_toggle,grp_led:scroll,compose:ralt us

[ -f ~/Pictures/background ] && feh --bg-max ~/Pictures/background
