#!/bin/bash

flameshot &

volumeicon &

## Set startup volume
pactl set-sink-volume 0 '20%' &

## Disable beeps
xset -b &

## DPMS monitor setting (standby -> suspend -> off) (seconds)
xset dpms 300 600 900 &

## Set LCD brightness
light -S 100 &

## Set the keyboard layouts, dvorak and us
setxkbmap dvorak,us -variant altgr-intl -option compose:ralt

[ -f ~/Pictures/background ] && feh --bg-scale ~/Pictures/background
