#!/bin/bash

KUBE_CONTEXT="$(kubectl config current-context 2> /dev/null)"
if [ "$KUBE_CONTEXT" ]; then
	KUBE_NAMESPACE="$(kubectl config view -o=jsonpath="{.contexts[?(@.name==\"$KUBE_CONTEXT\")].context.namespace}")"
	KUBE_CONTEXT="$KUBE_CONTEXT($KUBE_NAMESPACE)"
fi

echo $KUBE_CONTEXT
