#!/bin/bash

if [ -z $1 ]
then
    exit 0
fi

if [ $1 == "mute" ]
then
    CURRENT_STATE=$(amixer get Master | egrep 'Playback.*?\[o' | egrep -o '\[o.+\]')
    echo $CURRENT_STATE
    if [ -z $(echo "$CURRENT_STATE" | grep 'on') ]
    then
        amixer sset Master unmute
    else
        amixer sset Master mute
    fi
elif [ $1 == "up" ]
then
    amixer sset Master 5%+ unmute
elif [ $1 == "down" ]
then
    amixer sset Master 5%- unmute
fi
